Codes/Ecommerce (Vibe-Phone)/Ecommerce (Vibe-Phone) (Final-Project)/VibePhone/Controllers/BlogController.cs
namespace VibePhone.Controllers
{
    public class BlogController : Controller
    {
        public readonly IBlogRepo _BlogRepo;
        private readonly IMapper _Mapper;
        private readonly DBCONTEXT _DBCONTEXT;

        public BlogController(IBlogRepo blogRepo, IMapper iMapping, DBCONTEXT dBCONTEXT)
        {
            _BlogRepo = blogRepo;
            _Mapper = iMapping;
            _DBCONTEXT = dBCONTEXT;
        }

        //  ====================================================================
        //                                BlogAdd
        //  ====================================================================

        [HttpGet("AddBlog")]
        public IActionResult BlogAdd()
        {
            ViewBag.CategoryList = new SelectList(_DBCONTEXT.Categories, "CategoryId", "CategoryName");
            return View();
        }

        [HttpPost("AddBlog")]
        public IActionResult BlogAdd(ViewBlog model)
        {
            if (model.Image != null)
            {
                _BlogRepo.AddBlog(model);
                return Redirect($"{Url.Action("Index", "Dashboard")}#Blog");
            }
            ViewBag.CategoryList = new SelectList(_DBCONTEXT.Categories, "CategoryId", "CategoryName");
            return View(model);
        }



        //  ====================================================================
        //                                BlogUpdate
        //  ====================================================================

        [HttpGet("UpdateBlog")]
        public IActionResult BlogUpdate(int id)
        {
            var data = _BlogRepo.GetBlogById(id);
            if (data == null) return NotFound();

            var viewModel = _Mapper.Map<ViewBlog>(data);
            ViewBag.CategoryList = new SelectList(_DBCONTEXT.Categories, "CategoryId", "CategoryName", viewModel.CategoryId);
            return View(viewModel);
        }

        [HttpPost("UpdateBlog")]
        public IActionResult BlogUpdate(ViewBlog update)
        {
            if (update.Image != null)
            {
                _BlogRepo.UpdateBlog(update);
                return Redirect($"{Url.Action("Index", "Dashboard")}#Blog");
            }

            ViewBag.CategoryList = new SelectList(_DBCONTEXT.Categories, "CategoryId", "CategoryName");
            return View(update);
        }



        //  ====================================================================
        //                                BlogDelete
        //  ====================================================================

        [HttpGet("BlogDelete/{id}")]
        public IActionResult BlogDelete(int id)
        {
            var find = _BlogRepo.GetBlogById(id);
            if (find == null)
                return NotFound();

            return View(find);
        }

        [HttpPost]
        public IActionResult BlogDeleteConfirmed(int id)
        {
            _BlogRepo.DeleteBlog(id);
            return Redirect($"{Url.Action("Index", "Dashboard")}#Blog");
        }


    }
}

Codes/Ecommerce (Vibe-Phone)/Ecommerce (Vibe-Phone) (Final-Project)/VibePhone/Controllers/FeatureController.cs
namespace VibePhone.Controllers
{
    
    public class FeatureController : Controller
    {
        public readonly IFeatureRepo _FeatureRepo;
        private readonly IMapper _Mapper;
        private readonly DBCONTEXT _DBCONTEXT;

        public FeatureController(IFeatureRepo featureRepo, IMapper iMapping, DBCONTEXT dBCONTEXT)
        {
            _FeatureRepo = featureRepo;
            _Mapper = iMapping;
            _DBCONTEXT = dBCONTEXT;
        }

        //  ====================================================================
        //                                FeatureAdd
        //    ====================================================================

        [HttpGet("AddFeature")]
        public IActionResult FeatureAdd()
        {
            ViewBag.CategoryList = new SelectList(_DBCONTEXT.Categories, "CategoryId", "CategoryName");
            return View();
        }

        [HttpPost("AddFeature")]
        public IActionResult FeatureAdd(ViewFeature model)
        {
            if (model.Image != null)
            {
                _FeatureRepo.AddFeature(model);
                return Redirect($"{Url.Action("Index", "Dashboard")}#Feature");
            }
            ViewBag.CategoryList = new SelectList(_DBCONTEXT.Categories, "CategoryId", "CategoryName");
            return View(model);
        }


        //  ====================================================================
        //                                FeatureUpdate
        //    ====================================================================

        [HttpGet("UpdateFeature")]
        public IActionResult FeatureUpdate(int id)
        {
            var data = _FeatureRepo.GetFeatureById(id);
            if (data == null) return NotFound();
            var viewModel = _Mapper.Map<ViewFeature>(data);
            ViewBag.CategoryList = new SelectList(_DBCONTEXT.Categories, "CategoryId", "CategoryName", viewModel.CategoryId);
            return View(viewModel);
        }


        [HttpPost("UpdateFeature")]
        public IActionResult FeatureUpdate(ViewFeature Update)
        {
            if (Update.Image != null)
            {
                _FeatureRepo.UpdateFeature(Update);
                return Redirect($"{Url.Action("Index", "Dashboard")}#Feature");

            }
            ViewBag.CategoryList = new SelectList(_DBCONTEXT.Categories, "CategoryId", "CategoryName");
            return View(Update);
        }


        //  ====================================================================
        //                                FeatureDelete
        //    ====================================================================

        [HttpGet("FeatureDelete/{id}")]
        public IActionResult FeatureDelete(int id)
        {
            var find = _FeatureRepo.GetFeatureById(id);
            if (find == null)
                return NotFound();
            return View(find);
        }

        [HttpPost]
        public IActionResult FeatureDeleteConfirmed(int id)
        {
            _FeatureRepo.DeleteFeature(id);
            return Redirect($"{Url.Action("Index", "Dashboard")}#Feature");


        }

        //  ====================================================================
        //                                Single Product
        //    ====================================================================

        [HttpGet]
        public IActionResult SingleProduct(int id)
        {
            var product = _FeatureRepo.GetFeatureById(id);
            if (product == null) return NotFound();

            var vm = _Mapper.Map<ViewFeature>(product);
            ViewData["ImagePath"] = product.Image;
            return View(vm);
        }
    }
}

Codes/Ecommerce (Vibe-Phone)/Ecommerce (Vibe-Phone) (Final-Project)/VibePhone/Controllers/FrontController.cs
namespace VibePhone.Controllers
{
    public class FrontController : Controller
    {
        public readonly ISliderRepo _SliderRepo;
        public readonly IFeatureRepo _IFeatureRepo;
        public readonly ICategoryRepo _ICategoryRepo;
        public readonly IGalleryRepo _IGalleryRepo;
        public readonly IBlogRepo _IBlogRepo;
        public readonly ITestimonialRepo _ITestimonialRepo;
        public readonly INewslettersRepo _INewslettersRepo;

        public FrontController(ISliderRepo sliderRepo, IFeatureRepo featureRepo, ICategoryRepo categoryRepo,
            IGalleryRepo galleryRepo, IBlogRepo blogRepo, ITestimonialRepo testimonialRepo,
            INewslettersRepo newslettersRepo)

        {
            _SliderRepo = sliderRepo;
            _IFeatureRepo = featureRepo;
            _ICategoryRepo = categoryRepo;
            _IGalleryRepo = galleryRepo;
            _IBlogRepo = blogRepo;
            _ITestimonialRepo = testimonialRepo;
            _INewslettersRepo = newslettersRepo;
        }


        public IActionResult HomePage()
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");

            var vm = new ViewDashboard
            {
                Slider = _SliderRepo.GetAllSlider(),
                Feature = _IFeatureRepo.GetAllFeature(),
                Category = _ICategoryRepo.GetAllCategories(),
                Gallery = _IGalleryRepo.GetAllGallery(),
                Blog = _IBlogRepo.GetAllBlog(),
                Testimonial = _ITestimonialRepo.GetAllTestimonials(),
                Newsletter = _INewslettersRepo.GetAllNewsletter()
            };

            return View(vm);
        }
            
            
        
        [Route("AboutUs")]
        public IActionResult AboutUs() => View();

        [Route("Products")]
        public IActionResult Products()
        {
            var vm = new ViewDashboard
            {
                Gallery = _IGalleryRepo.GetAllGallery()
            };

            return View(vm);
        }

        [Route("Sony")]
        public IActionResult Sony()
        {
            var vm = new ViewDashboard
            {
                Gallery = _IGalleryRepo
                    .GetAllGallery()
                    .Where(g => g.Category.CategoryName == "Sony")
                    .ToList()
            };

            return View(vm);
        }

        [Route("Apple")]
        public IActionResult Apple()
        {
            var vm = new ViewDashboard
            {
                Gallery = _IGalleryRepo
                    .GetAllGallery()
                    .Where(g => g.Category.CategoryName == "Apple")
                    .ToList()
            };

            return View(vm);
        }

        [Route("Bose")]
        public IActionResult Bose()
        {
            var vm = new ViewDashboard
            {
                Gallery = _IGalleryRepo
                    .GetAllGallery()
                    .Where(g => g.Category.CategoryName == "Bose")
                    .ToList()
            };

            return View(vm);
        }

        [Route("Sennheiser")]
        public IActionResult Sennheiser()
        {
            var vm = new ViewDashboard
            {
                Gallery = _IGalleryRepo
                    .GetAllGallery()
                    .Where(g => g.Category.CategoryName == "Sennheiser")
                    .ToList()
            };

            return View(vm);
        }

        [Route("Blog")]
        public IActionResult Blog()
        {
            var vm = new ViewDashboard
            {
                Blog = _IBlogRepo.GetAllBlog()
            };

            return View(vm);
        }

        [Route("ContactUs")]
        public IActionResult ContactUs() => View();

        [Route("Faqs")]
        public IActionResult Faqs() => View();

        [Route("TermAndCondition")]
        public IActionResult TermAndCondition() => View();

        [Route("PrivacyPolicy")]
        public IActionResult PrivacyPolicy() => View();

    }
}

Codes/Ecommerce (Vibe-Phone)/Ecommerce (Vibe-Phone) (Final-Project)/VibePhone/Controllers/GalleryController.cs
namespace VibePhone.Controllers
{
    public class GalleryController : Controller
    {
        public readonly IGalleryRepo _GalleryRepo;
        private readonly IMapper _Mapper;
        private readonly DBCONTEXT _DBCONTEXT;

        public GalleryController(IGalleryRepo galleryRepo, IMapper iMapping, DBCONTEXT dBCONTEXT)
        {
            _GalleryRepo = galleryRepo;
            _Mapper = iMapping;
            _DBCONTEXT = dBCONTEXT;
        }

        //  ====================================================================
        //                                GalleryAdd
        //    ====================================================================

        [HttpGet("AddGallery")]
        public IActionResult GalleryAdd()
        {
            ViewBag.Categories = _DBCONTEXT.Categories.ToList();
            return View();
        }

        [HttpPost("AddGallery")]
        public IActionResult GalleryAdd(ViewGallery model)
        {
            if (model.ImageGallery != null)
            {
                _GalleryRepo.AddGallery(model);
                return Redirect($"{Url.Action("Index", "Dashboard")}#Gallery");

            }
            ViewBag.Categories = _DBCONTEXT.Categories.ToList();
            return View(model);
        }


        //  ====================================================================
        //                                GalleryDelete
        //    ====================================================================

        [HttpGet("GalleryDelete/{id}")]
        public IActionResult GalleryDelete(int id)
        {
            var find = _GalleryRepo.GetGalleryById(id);
            if (find == null)
                return NotFound();
            return View(find);
        }

        [HttpPost]
        public IActionResult GalleryDeleteConfirmed(int id)
        {
            _GalleryRepo.DeleteGallery(id);
            return Redirect($"{Url.Action("Index", "Dashboard")}#Gallery");

        }

        //  ====================================================================
        //                                Single Product
        //    ====================================================================

        [HttpGet]
        public IActionResult SingleProduct(int id)
        {
            var product = _GalleryRepo.GetGalleryById(id);
            if (product == null) return NotFound();

            var vm = _Mapper.Map<ViewGallery>(product); // ImagePath automatically filled
            return View(vm);
        }




    }
}

Codes/Ecommerce (Vibe-Phone)/Ecommerce (Vibe-Phone) (Final-Project)/VibePhone/Controllers/SliderController.cs
using System.IO;

namespace VibePhone.Controllers
{
    
    public class SliderController : Controller
    {
        public readonly ISliderRepo _SliderRepo;
        private readonly IMapper _Mapper;
        private readonly DBCONTEXT _DBCONTEXT;

        public SliderController(ISliderRepo SliderRepo, IMapper iMapping, DBCONTEXT dBCONTEXT)
        {
            _SliderRepo = SliderRepo;
            _Mapper = iMapping;
            _DBCONTEXT = dBCONTEXT;
        }

        //  ====================================================================
        //                                SliderAdd
        //    ====================================================================

        [HttpGet("AddSlider")]
        public IActionResult SliderAdd()
        {
            ViewBag.CategoryList = new SelectList(_DBCONTEXT.Categories, "CategoryId", "CategoryName");
            return View();
        }

        [HttpPost("AddSlider")]
        public IActionResult SliderAdd(ViewSlider model)
        {
            if (model.Image != null)
            {
                _SliderRepo.AddSlider(model);
                return RedirectToAction("Index", "Dashboard");
            }
            ViewBag.CategoryList = new SelectList(_DBCONTEXT.Categories, "CategoryId", "CategoryName");
            return View(model);
        }


        //  ====================================================================
        //                                SliderUpdate
        //    ====================================================================

        [HttpGet("UpdateSlider")]
        public IActionResult SliderUpdate(int id)
        {
            var data = _SliderRepo.GetSliderById(id);
            if (data == null) return NotFound();
            var viewModel = _Mapper.Map<ViewSlider>(data);
            ViewBag.CategoryList = new SelectList(_DBCONTEXT.Categories, "CategoryId", "CategoryName", viewModel.CategoryId);
            return View(viewModel);
        }


        [HttpPost("UpdateSlider")]
        public IActionResult SliderUpdate(ViewSlider Update)
        {
            if (Update.Image != null)
            {
                _SliderRepo.UpdateSlider(Update);
                return RedirectToAction("Index", "Dashboard");
            }
            ViewBag.CategoryList = new SelectList(_DBCONTEXT.Categories, "CategoryId", "CategoryName");
            return View(Update);
        }


        //  ====================================================================
        //                                SliderDelete
        //    ====================================================================

        [HttpGet("SliderDelete/{id}")]
        public IActionResult SliderDelete(int id)
        {
            var find = _SliderRepo.GetSliderById(id);
            if (find == null)
                return NotFound();
            return View(find);
        }

        [HttpPost]
        public IActionResult SliderDeleteConfirmed(int id)
        {
            _SliderRepo.DeleteSlider(id);
            return RedirectToAction("Index", "Dashboard");

        }

        //  ====================================================================
        //                                Single Product
        //    ====================================================================

        [HttpGet]
        public IActionResult SingleProduct(int id)
        {
            var product = _SliderRepo.GetSliderById(id);
            if (product == null) return NotFound();

            var vm = _Mapper.Map<ViewSlider>(product);
            ViewData["ImagePath"] = product.Image;
            return View(vm);
        }




    }
}

Codes/Ecommerce (Vibe-Phone)/Ecommerce (Vibe-Phone) (Final-Project)/VibePhone/Views/Front/Apple.cshtml
@model VibePhone.ViewModel.ViewDashboard

@{
    ViewData["Title"] = "Apple";
}

<!-- Banner -->
<div class="Banner" style="background-image: url('@Url.Content("~/Images/Newsletter.png")')">
    <h1>Apple</h1>
</div>

<!-- Products Sections -->

<section class="HomeContainer Gallerybgcolor">
    <div class="GalleryItems">
        @foreach (var item in Model.Gallery.GroupBy(f => f.ImageGallery).Select(g => g.First()))
        {
            <div class="ItemContainer">
                <div class="imagedetails">
                    <img src="@Url.Content("~/UploadImages/" + item.ImageGallery)">
                </div>
                <div class="productinfo">
                    <p class="productprice">$@item.Price</p>
                    <h3 class="productname">@item.ProductName</h3>
                    <p class="productcategory">@item.Category?.CategoryName</p>
                    <p class="PButton">
                        <a href="@Url.Action("SingleProduct", "Gallery", new { id = item.Id })">
                            Buy Now
                        </a>
                    </p>
                </div>
            </div>
        }
    </div>
</section>

Codes/Ecommerce (Vibe-Phone)/Ecommerce (Vibe-Phone) (Final-Project)/VibePhone/Views/Front/Blog.cshtml
@model VibePhone.ViewModel.ViewDashboard

@{
    ViewData["Title"] = "Blog";
}
<!-- Banner -->
<div class="Banner" style="background-image: url('@Url.Content("~/Images/Newsletter.png")')">
    <h1>Blog</h1>
</div>

<!-- blog Sections -->
<section class="BlogPage">

    <!-- Left Side: Blog Post -->
    <div class="postleft">
        @if (Model.Blog != null && Model.Blog.Any())
        {
            foreach (var item in Model.Blog)
            {
                <div class="blog-main">
                    <div class="blog-card">
                        <img src="@Url.Content("~/UploadImages/" + item.Image)" alt="@item.Title" class="blog-img" />
                        <p class="blog-category">@item.Category.CategoryName</p>
                        <h2 class="blog-title">@item.Title</h2>
                        <p class="blog-desc">@item.Description</p>
                        <a href="#" class="blog-btn">Read More</a>
                    </div>
                </div>
            }
        }
        else
        {
            <p>No blogs available.</p>
        }
    </div>

    <!-- Right Side: Latest Blogs -->
    <aside class="blog-sidebar">
        <h3>Latest Blogs</h3>
        <ul class="latest-list">
            @if (Model.Blog != null && Model.Blog.Any())
            {
                foreach (var item in Model.Blog)
                {
                    <li>
                        <a href="#">@item.Title</a>
                    </li>
                }
            }
            else
            {
                <li>No latest blogs found.</li>
            }
        </ul>
    </aside>

</section>

Codes/Ecommerce (Vibe-Phone)/Ecommerce (Vibe-Phone) (Final-Project)/VibePhone/Views/Front/Bose.cshtml
@model VibePhone.ViewModel.ViewDashboard

@{
    ViewData["Title"] = "Bose";
}

<!-- Banner -->
<div class="Banner" style="background-image: url('@Url.Content("~/Images/Newsletter.png")')">
    <h1>Bose</h1>
</div>

<!-- Products Sections -->

<section class="HomeContainer Gallerybgcolor">
    <div class="GalleryItems">
        @foreach (var item in Model.Gallery.GroupBy(f => f.ImageGallery).Select(g => g.First()))
        {
            <div class="ItemContainer">
                <div class="imagedetails">
                    <img src="@Url.Content("~/UploadImages/" + item.ImageGallery)">
                </div>
                <div class="productinfo">
                    <p class="productprice">$@item.Price</p>
                    <h3 class="productname">@item.ProductName</h3>
                    <p class="productcategory">@item.Category?.CategoryName</p>
                    <p class="PButton">
                        <a href="@Url.Action("SingleProduct", "Gallery", new { id = item.Id })">
                            Buy Now
                        </a>
                    </p>
                </div>
            </div>
        }
    </div>
</section>

Codes/Ecommerce (Vibe-Phone)/Ecommerce (Vibe-Phone) (Final-Project)/VibePhone/Views/Front/HomePage.cshtml
@model VibePhone.ViewModel.ViewDashboard
@{
    ViewData["Title"] = "Home";
}                            

                                                @* Slider Section *@

<section class="SliderContainer">
        @foreach (var item in Model.Slider.GroupBy(f => f.Title).Select(g => g.First()).Take(6))
    {
        <div class="CaroselSlider @(item == Model.Slider.First() ? "active" : "")" style="background-image:url('@Url.Content("~/UploadImages/" + item.Image)')">
            <div class="SliderItems">
                <p class="Price">$@item.Price</p>
                <h1 class="Title">@item.Title</h1>
                <p class="Description">@item.Description</p>
                <div class="Sliderbutton">
                    <a href="@Url.Action("SingleProduct", "Slider", new { id = item.Id })">
                        Buy Now
                    </a>
                    @* <a asp-controller="Front" asp-action="Products">Buy Now</a> *@
                    <a asp-controller="Front" asp-action="Products">All Products</a>
                </div>
            </div>
        </div>
    }

    <div class="slider-dots">
        @for (int i = 0; i < Model.Slider.Count; i++)
        {
            <span class="dot @(i == 0 ? "active" : "")"></span>
        }
    </div>
</section>

                                                <!-- Feature-Section -->

    <section class="HomeContainer">
        <div class="SectionHead">
            <p>FEATURE PRODUCTS</p>
        <a asp-controller="Front" asp-action="Products">SEE ALL PRODUCTS</a>
        </div>

        <div class="FeatureItems">

        @foreach (var item in Model.Feature.GroupBy(f => f.Title).Select(g => g.First()).Take(12))
        {
            <div class="ItemContainer">
                <div class="imagedetails">
                    <a asp-controller="Front" asp-action="Products">
                        <img src="@Url.Content("~/UploadImages/" + item.Image)" alt="@item.Title">
                    </a>
                </div>
                <div class="Itemdetails">
                    <p class="PPrice">$@item.Price</p>
                    <p class="PName">@item.Title</p>
                    @* <p class="PDescription">@item.Description</p> *@
                    <p class="PButton">
                        <a href="@Url.Action("SingleProduct", "Feature", new { id = item.Id })">
                            Buy Now
                        </a>
                        @* <a href="#">Add to Cart</a> *@
                    </p>
                </div>
            </div>
        }
    </div>
    </section>

                                                 <!-- Gallery-Section -->

    <section class="HomeContainer Gallerybgcolor">
        <div class="SectionHead">
            <p>GALLERY</p>
        <a asp-controller="Front" asp-action="Products">SEE ALL PRODUCTS</a>
        </div>

        <div class="GalleryItems">

            <!-- Img1 -->
        @foreach (var item in Model.Gallery.GroupBy(f => f.ImageGallery).Select(g => g.First()).Take(24))
        {
            <div class="ItemContainer">
                <div class="imagedetails">
                    <a asp-controller="Front" asp-action="Products">
                        <img src="@Url.Content("~/UploadImages/" + item.ImageGallery)">
                    </a>
                </div>
                <div class="Itemdetails">
                    <p class="PPrice">$@item.Price</p>
                    <p class="PName">@item.ProductName</p>
                    @* <p class="PDescription">@item.Description</p> *@
                    <p class="PButton">
                        <a href="@Url.Action("SingleProduct", "Gallery", new { id = item.Id })">
                            Buy Now
                        </a>
                    </p>
                </div>
            </div>
        }
    </section>

                                                <!-- Why Choose US -->

<section class="ChooseusContainer" style="background-image: url('@Url.Content("~/Images/ChooseUS.png")')">
    <div class="SectionHead">
        <p>WHY CHOOSE US</p>
    </div>
    <div class="Chooseus-Box-Container">
        <div class="Chooseus-Box">
            🚚 <p>Free Shipping</p>
        </div>
        <div class="Chooseus-Box">
            🛡️ <p>1-Year Warranty</p>
        </div>
        <div class="Chooseus-Box">
            🔄 <p>Easy Returns</p>
        </div>
        <div class="Chooseus-Box">
            🔒 <p>Secure Payments</p>
        </div>
        <div class="Chooseus-Box">
            📞 <p>24/7 Support</p>
        </div>
    </div>

</section>


    <!-- Testimonials -->

    <section class="TestimonialsContainer">
    
        <div class="SectionHead"><p>TESTIMONIALS</p></div>
        <div class="Testimonials-Box-Container">

        @foreach (var item in Model.Testimonial.GroupBy(f => f.Title).Select(g => g.First()).Take(6))
        {
            <div class="Testimonials-Box">
                <img src="@Url.Content("~/Images/DefaultImage.png")">
                <p class="tName">- @item.Title</p>
                <p class="tDescription">@item.Description</p>
            </div>
        }


        </div>
    </section>

    <!-- NewsLetter -->

<section class="NewsLetterContainer" style="background-image: url('@Url.Content("~/Images/ChooseUS.png")')">
    <div class="SectionHead">
        <p>NEWS LETTER</p>
    </div>

    <div class="newsletter-content">
        <h2>Subscribe To Our News Letter</h2>
        <p>You never miss our latest updates, offers, and product launches.</p>

        <form asp-controller="Dashboard" asp-action="NewsletterAdd" method="post" class="newsletter-form">
            <input asp-for="Newsletters.Email" type="email" class="feature-field" placeholder="Enter Your Email" required>
            <button type="submit">SUBSCRIBE</button>
        </form>

    </div>
</section>

Codes/Ecommerce (Vibe-Phone)/Ecommerce (Vibe-Phone) (Final-Project)/VibePhone/Views/Front/Products.cshtml
@model VibePhone.ViewModel.ViewDashboard
@{
    ViewData["Title"] = "Products";
}

<!-- Banner -->
<div class="Banner" style="background-image: url('@Url.Content("~/Images/Newsletter.png")')">
    <h1>Products</h1>
</div>

<!-- Products Sections -->
<section class="HomeContainer Gallerybgcolor">
    <div class="GalleryItems">
        @foreach (var item in Model.Gallery.GroupBy(f => f.ImageGallery).Select(g => g.First()))
        {
            <div class="ItemContainer">
                <div class="imagedetails">
                    <a href="@Url.Action("SingleProduct", "Gallery", new { id = item.Id })">
                        <img src="@Url.Content("~/UploadImages/" + item.ImageGallery)" alt="@item.ProductName" />
                    </a>
                    <div class="productinfo">
                        <p class="productprice">$@item.Price</p>
                        <h3 class="productname">@item.ProductName</h3>
                        <p class="productcategory">@item.Category?.CategoryName</p>
                        <p class="PButton">
                            <a href="@Url.Action("SingleProduct", "Gallery", new { id = item.Id })">
                                Buy Now
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        }

    </div>
</section>

Codes/Ecommerce (Vibe-Phone)/Ecommerce (Vibe-Phone) (Final-Project)/VibePhone/Views/Front/Sennheiser.cshtml
@model VibePhone.ViewModel.ViewDashboard

@{
    ViewData["Title"] = "Sennheiser";
}

<!-- Banner -->
<div class="Banner" style="background-image: url('@Url.Content("~/Images/Newsletter.png")')">
    <h1>Sennheiser</h1>
</div>

<!-- Products Sections -->

<section class="HomeContainer Gallerybgcolor">
    <div class="GalleryItems">
        @foreach (var item in Model.Gallery.GroupBy(f => f.ImageGallery).Select(g => g.First()))
        {
            <div class="ItemContainer">
                <div class="imagedetails">
                    <img src="@Url.Content("~/UploadImages/" + item.ImageGallery)">
                </div>
                <div class="productinfo">
                    <p class="productprice">$@item.Price</p>
                    <h3 class="productname">@item.ProductName</h3>
                    <p class="productcategory">@item.Category?.CategoryName</p>
                    <p class="PButton">
                        <a href="@Url.Action("SingleProduct", "Gallery", new { id = item.Id })">
                            Buy Now
                        </a>
                    </p>
                </div>
            </div>
        }
    </div>
</section>

Codes/Ecommerce (Vibe-Phone)/Ecommerce (Vibe-Phone) (Final-Project)/VibePhone/Views/Front/Sony.cshtml
@model VibePhone.ViewModel.ViewDashboard

@{
    ViewData["Title"] = "Sony";
}

<!-- Banner -->
<div class="Banner" style="background-image: url('@Url.Content("~/Images/Newsletter.png")')">
    <h1>Sony</h1>
</div>

<!-- Products Sections -->

<section class="HomeContainer Gallerybgcolor">
    <div class="GalleryItems">
        @foreach (var item in Model.Gallery.GroupBy(f => f.ImageGallery).Select(g => g.First()))
        {
            <div class="ItemContainer">
                <div class="imagedetails">
                    <img src="@Url.Content("~/UploadImages/" + item.ImageGallery)">
                </div>
                <div class="productinfo">
                    <p class="productprice">$@item.Price</p>
                    <h3 class="productname">@item.ProductName</h3>
                    <p class="productcategory">@item.Category?.CategoryName</p>
                    <p class="PButton">
                        <a href="@Url.Action("SingleProduct", "Gallery", new { id = item.Id })">
                            Buy Now
                        </a>
                    </p>
                </div>
            </div>
        }
    </div>
</section>